# Site settings
title: A funny developer # the main title
description: >- # used by seo meta and the atom feed
  Enjoy life with ⌨️ and 💡
lang: en-US # default lang
timezone: Asia/Saigon # set your timezone
image: assets/img/thumb.webp # This image used for Open Graph more info https://ogp.me/
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Quang # author name
  bio: >- # tell to the world
     Enjoy life with ⌨️ and 💡
  username: quangpl # general username
  github: quangpl # github username
  twitter: quangpl99 # twitter username
  facebook: quangpl99 # facebook username
  email: phanlequang99@gmail.com # email adress
  avatar: /assets/img/avatar.png # change with your own avatar

# URL settings
url: "https://quangpl.github.io" #
baseurl:
permalink: /:title/
google_analytics: G-KJ02KMPY6M# leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
